/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@class CUIRenditionKey, NSString;

@interface CUINamedImage : NSObject {
    CUIRenditionKey *_key;
    NSString *_name;
    unsigned long long _storageRef;
}

@property(readonly) int blendMode;
@property(readonly) int exifOrientation;
@property(readonly) bool hasSliceInformation;
@property(readonly) long long imageType;
@property(readonly) bool isStructured;
@property(readonly) bool isTemplate;
@property(readonly) bool isVectorBased;
@property(copy) NSString * name;
@property(readonly) double opacity;
@property(readonly) long long resizingMode;
@property(readonly) double scale;
@property(readonly) long long templateRenderingMode;
@property NSSize size;

- (id)UIImage;
- (id)_rendition;
- (id)_themeStore;
- (struct { double x1; double x2; double x3; double x4; })alignmentEdgeInsets;
- (id)baseKey;
- (int)blendMode;
- (void)dealloc;
- (id)description;
- (struct { double x1; double x2; double x3; double x4; })edgeInsets;
- (int)exifOrientation;
- (long long)graphicsClass;
- (bool)hasSliceInformation;
- (long long)idiom;
- (struct CGImage { }*)image;
- (long long)imageType;
- (id)initWithName:(id)arg1 usingRenditionKey:(id)arg2 fromTheme:(unsigned long long)arg3;
- (bool)isStructured;
- (bool)isTemplate;
- (bool)isVectorBased;
- (long long)memoryClass;
- (id)name;
- (double)opacity;
- (double)positionOfSliceBoundary:(unsigned int)arg1;
- (id)renditionKey;
- (long long)resizingMode;
- (double)scale;
- (void)setName:(id)arg1;
- (long long)sizeClassHorizontal;
- (long long)sizeClassVertical;
- (unsigned long long)subtype;
- (long long)templateRenderingMode;
- (id)traitCollection;

@end
